# Generated by Django 5.1.2 on 2024-10-20 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_profile_date_of_birth_profile_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='photo',
        ),
    ]
