# Generated by Django 5.1.2 on 2024-11-08 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0008_alter_person_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='completed_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
